version: '3'
services:
  spring-boot:
    image: "bootdocker:8"
    ports:
     - "8080:8080"
    container_name: spring-boot
  prometheus:
    image: "prom/prometheus"
    ports:
     - "9090:9090"
    volumes:
     - ./prom.yml:/etc/prometheus/prometheus.yml
    container_name: prometheus
  alertmanager:
    image: prom/alertmanager:v0.23.0
    ports:
      - "9093:9093"
    volumes:
      - "./alertmanager:/config"
      - alertmanager-data:/data
    command: --config.file=/config/alertmanager.yml --log.level=debug
    container_name: alertmanager
  grafana:
     image: "grafana/grafana"
     ports:
     - "3000:3000"
     container_name: grafana
volumes:
  alertmanager-data:

